### ISSUE TITLE
Parse errors no security at MinimalCompact/thumbor/blob/master/thumbor/conf/thumbor.conf.tpl

### ISSUE THREAD

**Issue by frankii91** [MinimalCompact/thumbor#138]
Parse errors no security at MinimalCompact/thumbor/blob/master/thumbor/docker-entrypoint.sh

As such, it's not entirely a bug but a problem for beginners, using the documentation and basic information can be easily cut not to use apostrophes at the beginning and end ...

np.
Docker compose
 environment:
  - PILLOW_RESAMPLING_FILTER=LANCZOS

 vs
 environment:
  - PILLOW_RESAMPLING_FILTER='LANCZOS'  

will give an error even though - apostrophes, singles or doubles are imperfect, the script itself should detect and remove them from the beginning and end...

can something be done about it?
What for  ?
docker compose linking your configuration file to /app/thumbor.conf

it's not working for me, can i have some env? so that it can be done?

**Comment by gingerlime** [comment]
I'm not sure I understand the question/suggestion. I think the typical audience for using / configuring thumbor is familiar with different configuration formats.

**Comment by frankii91** [comment]
śr., 16 sie 2023 o 09:13 gingerlime ***@***.***> napisał(a):

**Comment by frankii91** [comment]
Rather typical users use their customized versions and those who start may
have a lot of trouble....
just like me when I started - the team already knows a lot ... but at the
beginning I lost a lot of time .... because of ambiguity

śr., 16 sie 2023 o 20:04 Krzysztof Wielgosz ***@***.***>
napisał(a):

**Comment by gingerlime** [comment]
from https://github.com/MinimalCompact/thumbor/issues/87#issuecomment-687003403 (adapted slightly)

If you don't already have a thumbor.conf file, I guess best option is to grab the default one from the thumbor project? Then to use your own thumbor.conf file, you can simply mount it with docker, e.g.

docker run -p 80:80 -v /path/to/your/thumbor.conf:/app/thumbor.conf ghcr.io/minimalcompact/thumbor

Otherwise, you set up environment variable to only override any of the defaults.

**Comment by gingerlime** [comment]
closing for now, but please feel free to re-open if it's still a problem
