### ISSUE TITLE
Migrate to `thumbor-aws`

### ISSUE THREAD

**Issue by phoenisx** [MinimalCompact/thumbor#153]
`thumbor-aws` is officially supported by `thumbor` project, while `tc-aws` hasn't been maintained for 2 years.

Should we migrate into using `thumbor-aws`?

I know this would be a breaking change, so should we support both of them for the next release but deprecate the usage of one over the other and remove it completely in the next major release?

**Comment by gingerlime** [comment]
Can `thumbor-aws` create a compatibility layer of some sort? this could make the transition much easier.

**Comment by phoenisx** [comment]
I am not sure. I am pretty new to this ecosystem, and have long forgotten working with Python 🥲.

Anyways, I am fiddling with my custom docker image to make `thumbor_aws` work, but I am facing some issue setting up `thumbor_aws` with Thumbor's Lazy detectors enabled.
Since `thumbor_aws` uses `tc_redis`, there are some clashes with Redis ENV variables we are using in the service I guess.
Not sure still debugging why I am not able to fetch `/smart/*` URLs. Without Lazy detectors everything was working fine before 😭

**Comment by gingerlime** [comment]
To my knowledge `/smart/` URLs rely on `remotecv`, so perhaps it's missing in your setup?

**Comment by phoenisx** [comment]
Thanks for the response @gingerlime.

I was able to set this up somehow, but I had to revert my changes coz somehow enabling `smart` queued images disabled caching the results, due to which my servers were getting a lot of load.

I found the fix in the docs itself: https://github.com/thumbor/thumbor-aws?tab=readme-ov-file#configuring-thumbor-in-compatibility-mode-with-tc_aws
`thumboar-aws` does have compatibility with `tc_aws`, but with one caveat, that it does not support creating new buckets.

Anyways, Since I had to revert my changes, and have completely forgotten how I did make things work (my bad 😅), I would suggest closing this issue for now.
We can re-open it once I get time to experiment with Thumbor again.

Apologies for the inconvenience 🙇🏽

**Comment by gingerlime** [comment]
No inconvenience at all, and we're looking for this kind of contribution, so we can upgrade dependencies and stay with the latest libraries. It's definitely worthwhile. So if you're up for creating a PR and helping with the docs so people who upgrade don't run into issues (or keeping both versions for compatibility, at least for a while), I'm all for it!

I'll close it for now, but not because I'm not interested. Just that I'm not sure I can pick this up entirely on my own and would need someone to take the lead here.

Thanks again @phoenisx
