### ISSUE TITLE
Injection of basic auth header by nginx-proxy

### ISSUE THREAD

**Issue by alexjet** [MinimalCompact/thumbor#18]
We use thumbor with image sources that are secured with basic authorisation. Since thumbor doesn't support such option out of the box, we have to use something additionally around it.

Recently I found your suggestion to inject a header in front of thumbor here:
https://github.com/thumbor/thumbor/issues/1100

But since in a package there is nginx-proxy as a frontend proxy, could you extend its functionality with the option to pass a user:password or a hash to be injected in an upstreaming request to thumbor? Then we don't need to set up any additional containers and this option could be useful for some other artisans as well ;)

**Comment by kkopachev** [comment]
Even if you inject basic auth into upstream request's original path, that would change signature. If you're using it, of course.

I think that solution would be too much edge case to be included in here. This project is meant to be good way to cover most common cases. If something unique required, then it's easy to build new layer on top with custom functionality.

**Comment by gingerlime** [comment]
Sorry it took me some time to respond. I was off sick with a flu.

I agree with @kkopachev on this one. I don't think it belongs here. Btw, the nginx-proxy on this project sits in front of thumbor, rather than between thumbor and your backend. 

I would imagine writing your own `http_loader` is the best option here, and then you can build your own docker image based on this in order to use it. That said, I do wonder if there's a way to make adding 3rd party libraries easier... But that's a much broader question.

I'll close this one for now, if you don't mind.
