### ISSUE TITLE
Any there any differences between apsl/thumbor and minimalcompact/thumbor?

### ISSUE THREAD

**Issue by dloeng** [MinimalCompact/thumbor#26]
We have a production service that uses an image whose parent is `apsl/thumbor:6.4.2-simd-avx2`.

Recently, we've had issues building this image due to the EOL-ing of Debian jessie. 

I noticed that minimalcompact/thumbor:6.4.2-simd-avx2 is already on Debian stretch 👍and we are considering whether to use this as the parent image instead. 

I am comparing the single Dockerfile in this project and the multiple Dockerfiles in the apsl project. Could you help me understand the differences (as slight as they may be)?

**Comment by gingerlime** [comment]
Hey @dloeng !

As far as I'm aware, APSL/thumbor is no longer maintained. I tried to reach out to the maintainer a number of times and have had basically no response. Here's the [latest attempt](https://github.com/APSL/docker-thumbor/issues/103) :)

Also, I think the latest tag on APSL is 6.4.2, but thumbor has moved on, so this project tries to keep up with the latest thumbor releases.

In terms of splitting things, I used a slightly different structure. See https://github.com/MinimalCompact/thumbor#minimal-compact-thumbor - so for example, we use one image for both single and multiprocess and it picks which one it runs with based on [`THUMBOR_NUM_PROCESSES`](https://github.com/MinimalCompact/thumbor/blob/master/thumbor/docker-entrypoint.sh#L24). We also use an image based on [nginx-proxy](https://github.com/jwilder/nginx-proxy) and I believe APSL was using one based on nginx.

In general, this project should offer a more actively-maintained near-drop-in-replacement.

We also try to maintain some [recipes](https://github.com/MinimalCompact/thumbor/tree/master/recipes) for doing things (contributions are welcome!), and I hope to also build a community and best-practice information around deployments, performance optimisation etc. Admittedly. the latter is more wishful thinking at this point due to time constraints and relatively few contributors so far. But it can change :)
