### ISSUE TITLE
How to setup variables on this docker version?

### ISSUE THREAD

**Issue by planetahuevo** [MinimalCompact/thumbor#27]
I am really new to docker and I could not find anything about variables on your setup instructions. 
Can you please link me to the right place to find out the variables that this docker accepts?

Thanks!

**Comment by gingerlime** [comment]
Hey @planetahuevo !

Not entirely sure I understand the question fully, but since you're saying you're new to docker, I would just recommend reading https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers as well as https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

You can also take a look at how to set up [environment variables with docker-compose](https://docs.docker.com/compose/environment-variables/) (think of docker-compose as a way to combine multiple docker containers together, as well as define how they are linked together, their environment variables etc). there are some [example recipes for docker-compose](https://github.com/MinimalCompact/thumbor/tree/master/recipes/docker-compose) as well on this repo, and you can see some environment variables being defined there as well.

Hope this helps!

**Comment by planetahuevo** [comment]
Thank you very much for the links! :) 
Yeah I am just learning at the same time I am asking. 

Let me clarify my question, but I think you have already answered it. 
On APSL/docker-thumbor there is this list:
https://github.com/APSL/docker-thumbor#env-vars-and-default-value

On your instructions that list does not appear, so Iwas not sure if those Envs vars were available or not. 
By your answer I suppose they always are, and checking the recipes confirm that for me. 👍 

Thank you very much for answering so good and understanding that my question was not "properly made" because I do not know anything. :)

**Comment by gingerlime** [comment]
We all have to start from somewhere, so don't worry... :)

Now that you explained, I think I understand better. 

The mapping of variables is the same as APSL's pretty much (with some addition and small modifications). You can find the list of variables here: https://github.com/MinimalCompact/thumbor/blob/master/thumbor/conf/thumbor.conf.tpl - and those variables should match those on thumbor itself, which you can find here: https://github.com/thumbor/thumbor/blob/master/thumbor/config.py

Hope this makes things a bit clearer.

**Comment by planetahuevo** [comment]
Yep! Thanks!
