### ISSUE TITLE
nginx-proxy (version 6.7.0) returns default content-type application/octet-stream

### ISSUE THREAD

**Issue by limuhob** [MinimalCompact/thumbor#45]
Thumbor changed result_storage filename format and files has no longer type extensions (.jpeg, .png). Therefor nxing-proxy returns default content-type application/octet-stream instead of e.g. image/jpg.

**Comment by gingerlime** [comment]
@limuhob oh dear. You're right.

I wasn't very keen on the change to caching (see #19), but here's another edge-case that gets broken if we can't know the cached file-type any more ... 

The problem is that the requested filename doesn't always represent the actual cached format, especially with some of the AUTO_* (AUTO_PNG_TO_JPG, AUTO_WEBP maybe a few more?), as well as using `filters:format(...)` and maybe a few other edge cases?

@kkopachev what do you think? is it something worth bringing to thumbor upstream?

**Comment by limuhob** [comment]
Hi, I have created pull request https://github.com/MinimalCompact/thumbor/pull/48 that seems to fix this problem for my purposes if you are interested.

**Comment by limuhob** [comment]
Hi @gingerlime , sorry for delay.  This line https://github.com/MinimalCompact/thumbor/blob/07430a08ffb6297943c2075d2419fd2ed0b1f3f4/nginx-proxy/nginx.conf#L17 should be `default_type  "";` otherwise nginx returns the content-type header twice with differrent values. E.g. application/octet-stream and image/jpg.

**Comment by gingerlime** [comment]
@limuhob I think it works as expected with https://github.com/MinimalCompact/thumbor/commit/b1dc1863aaba0bc74674f0d64ffbaea23a0c4675 (and I added tests for it)

If it's not working, can you create a test that demonstrates the issue?

**Comment by limuhob** [comment]
Yes. I have created pull request with test.
