### ISSUE TITLE
How to configure to use file loader?

### ISSUE THREAD

**Issue by wintercounter** [MinimalCompact/thumbor#70]
Some documentation in configuration would be highly appreciated because now it's almost 0 besides installation and the recipes.

**Comment by gingerlime** [comment]
Thanks for your feedback. PRs are welcome. If you have some ideas on how to improve documentation, I'd be happy to consider them. 

Most documentation exists on the main thumbor project, because this is just a docker image of it, and by and large we just pass over whatever configuration there is. Specifically things like loaders etc are documented on the thumbor project as far as I'm aware. There's nothing specific to the docker image about it I would say.

**Comment by gingerlime** [comment]
closing due to lack of response
