### ISSUE TITLE
Loading big image over proxy times out

### ISSUE THREAD

**Issue by pscheit** [MinimalCompact/thumbor#79]
Hi there,

i recently switched to your thumbor image. Now I get the following for some big images:

```
nginx_1     | nginx.1    | 2020/05/30 03:35:59 [error] 56#56: *7870 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.5.1, server: localhost, request: "GET /dV1EGhpGw6RV4JX6jGeYkZhJ3M0=/fit-in/12000x12000/filters:quality(100)/hochzeit-julia-und-ulrich-3.jpg HTTP/1.1", upstream: "http://192.168.96.2:80/dV1EGhpGw6RV4JX6jGeYkZhJ3M0=/fit-in/12000x12000/filters:quality(100)/hochzeit-julia-und-ulrich-3.jpg", host: "images.xxx.xx"
```
I request 5 images at the same time. They are like 10mb each unpacked 65mb (5800x3968)

do i need to increase the nginx timeouts? Do you have an idea how to do it with jwilder/proxy ?
don't we have to use the fastcgi upstream?

**Comment by pscheit** [comment]
oh, it's converting to webp when showing this images

**Comment by gingerlime** [comment]
are you using `thumbor-nginx-proxy-cache`? can you share a reproducible config? (e.g. docker-compose.yml file with a sample image)

to tweak the proxy timeouts, you would need a [custom configuration](https://github.com/nginx-proxy/nginx-proxy#custom-nginx-configuration) (either globally or per virtual host) and customize your proxy timeouts.

**Comment by pscheit** [comment]
yes. The config is the remotecv config in recipes. I have webp enabled and requesting 5 10mb images at once. 
I have 4 processes in thumbor, but still the conversion is too slow to not exceed the timeout (i think).  When I request them individually it takes time, too, but it works. So it's a real timeout issue on my side, i guess

**Comment by gingerlime** [comment]
How many CPUs do you have? 

You can tweak the timeout, but in a way you'll be treating the symptoms rather than the real issue. You probably want images to load fast enough. Also, the larger the timeout, and the more concurrent requests you're getting, the bigger the stress over your CPUs can become, so you could end up making things worse. This is part of fine-tuning your setup based on the images you use, the request patterns/frequency, your hardware etc.

btw, from my experience there's very little noticeable difference with quality if you set it above 85 or so, but that's another thing you need to experiment with and see for your use-case.

Hope you can figure things out. If you can share what you found this can be useful for others in future.

**Comment by pscheit** [comment]
yes, i think i have to finetune here. I'm currently using processes == $(nproc) and having a load balancer that scales between two thumbor instances.

But usually I don't need to resize so many images on the fly, when my precaching works. I was just confused whats happening.

Increasing the timeout allows to have the images displayed at least.

I can decrease the resolution for my case and will decrease the quality, but the main task to render the jpg to webp is what's taking here so long (i guess?)
so decreasing the quality will just decrease the filesize, but not the render-time (maybe)

Thanks for helping!
